# Generated by Django 5.0 on 2023-12-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SentimentReconrd',
            new_name='SentimentRecord',
        ),
    ]
